dist: xenial
sudo: false
language: python
python: 3.7
cache: pip

before_install:
  - pip install -r requirements-tests-py3.txt

install:
  - pip install .

script:
  - ./tests/mypy_test.py
  - MYPY_TEST_PREFIX=$PWD MYPYPATH=$PWD/third_party/3 pytest
