sudo: false
language: python
cache: pip

dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

before_install:
  - pip install -r requirements-tests-py3.txt

install:
  - pip install .

script: ./tests/mypy_test.py
