sudo: false
language: python

matrix:
  include:
    - python: "3.7"    
    - python: "3.6"
    - python: "3.5"

install:
  - pip install .
  - pip install -r requirements-tests-py3.txt

script: ./tests/mypy_test.py
