name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue haven't seen any activity in a while."
        stale-pr-message: "This pull request haven't seen any activity in a while."
        stale-issue-label: "stale"
        stale-pr-label: "stale"
